# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main'] # Or your default branch name

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # Removed defaults block
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Add step to list files for debugging path issues
      - name: List files in workspace
        run: ls -la
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Use Node.js 20 or your preferred version
          cache: 'npm'
          # Use glob pattern to find package-lock.json in any subdirectory
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        # Explicitly cd into the directory before running npm install
        run: cd mopres-nextjs && npm install
      - name: Build and Export
        # Explicitly cd into the directory before running npm run build
        run: cd mopres-nextjs && npm run build
        env:
          # If you have build-time environment variables, add them here
          # NEXT_PUBLIC_EXAMPLE_VAR: ${{ secrets.EXAMPLE_VAR }}
          # Make sure to add corresponding secrets in your repository settings
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      # Add this new step to create .nojekyll file
      - name: Create .nojekyll file
        run: touch mopres-nextjs/out/.nojekyll # Removed leading ./
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the exported 'out' directory from your Next.js project
          path: 'mopres-nextjs/out' # Removed leading ./
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
